version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Prep
	  command: sudo apt-get install -y make gcc perl
      - checkout
      - run:
          name: Build+test
          command: make all

