version: 2.1

commands:
  testrun:
    steps:
      - attach_workspace:
          at: /dist
      - run:
          name: Installation test
          command: find /dist -name *.rpm | fgrep -v .src.rpm | xargs yum install -y
      - run:
          name: Install git
          command: yum install -y git
      - checkout
      - run:
          name: Test preparation
          command: .circleci/testprep.sh
      - run:
          name: Distribution validity test
          command: make disttest

jobs:
  build:
    docker:
      - image: centos:latest
    working_directory: ~/repo
    steps:
      - run:
          name: Install basic build tools
          command: |
            yum install -y git
      - checkout
      - run:
          name: Install dependencies
          command: |
            command -v yum-builddep || yum install -y /usr/bin/yum-builddep
            yum-builddep -y *.spec
      - run:
          name: Build RPM
          command: |
            rm -f *.rpm
            tar -zcvf /tmp/retry.tar.gz *
            rpmbuild -ta /tmp/retry.tar.gz
            make -j2
            mkdir -p /dist/.
            find /root/rpmbuild -name *.rpm | xargs -I RPM -n 1 -P10 mv -v RPM /dist/
            mv -v retry /dist/
      - persist_to_workspace:
          root: /dist/
          paths: ./*

  test7:
    docker:
      - image: centos:centos7
    steps:
      - testrun

  test8:
    docker:
      - image: centos:centos8
    steps:
      - testrun

  github-publish:
    docker:
      - image: cibuilds/github:0.13
    steps:
      - checkout
      - attach_workspace:
          at: /dist
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(git tag | tail -n 1)
            test -n "$VERSION"
            test -n "$GITHUB_TOKEN"
            test -n "$CIRCLE_PROJECT_USERNAME"
            test -n "$CIRCLE_PROJECT_REPONAME"
            test -n "$CIRCLE_SHA1"
            echo ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /dist/

  finalize:
    docker:
      - image: centos:latest
    steps:
      - attach_workspace:
          at: /dist
      - run:
          name: Move to final location
          command: |
            mkdir -p final
            mv /dist/*.rpm final/
      - store_artifacts:
          path: final/
          destination: /

workflows:
  version: 2.1
  on-commit:
    jobs:
      - build
      - test7:
          requires:
            - build
      - test8:
          requires:
            - build
      - github-publish:
          filters:
            branches:
              only: master
          requires:
            - test7
            - test8
      - finalize:
          requires:
            - test7
            - test8
