version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Show stuff
          command: whoami && pwd && dpkg -l | sort
      - run:
          name: Prep
          command: apt-get install -y make gcc perl-base
      - checkout
      - run:
          name: Build+test
          command: make all

