version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
        command: [bash -c 'apt-get install -y make gcc perl']
    steps:
      - checkout
      - run:
          name: Build+test
          command: make all

