version: 2
jobs:
  build:
    docker:
      - image: centos:latest
    steps:
      - run:
          name: Show stuff
          command: whoami && pwd && ( ( dpkg -l || rpm -qa ) | sort )
      - run:
          name: Prep
          command: ( apt-get update && apt-get install -y git ) || yum -y install yum-utils git
      - checkout
      - run:
          name: Install build dependencies
          command: ( apt-get install -y make gcc perl-base || yum-builddep -y *.spec )
      - run:
          name: Build+test
          command: make all

