version: 2.1
jobs:
  build:
    docker:
      - image: centos:latest
    working_directory: ~/repo
    steps:
      - run:
          name: Install basic build tools
          command: |
            yum install -y git
      - checkout
      - run:
          name: Install dependencies
          command: |
            command -v yum-builddep || yum install -y /usr/bin/yum-builddep
            yum-builddep -y *.spec
      - run:
          name: Build RPM
          command: |
            rm -f *.rpm
            tar -zcvf /tmp/retry.tar.gz *
            rpmbuild -ta /tmp/retry.tar.gz
            mkdir -p dist
            find /root/rpmbuild -name *.rpm | xargs -I RPM -n 1 -P10 mv -v RPM dist/
      - persist_to_workspace:
          root: dist/
          paths: ./*.rpm

  test7:
    docker:
      - image: centos7:latest
    steps:
      - run:
          name: Install basic tools
          command: |
            yum install -y git
      - checkout
      - attach_workspace:
          at: dist/
      - run:
          name: Test preparation
          command: .circleci/testprep.sh
      - run:
          name: Installation test
          command: find dist/ -name *.rpm | fgrep -v .src.rpm | xargs yum install -y
      - run:
          name: Distribution validity test
          command: |
            make disttest
      - store_artifacts:
          path: final/
          destination: /

  test8:
    docker:
      - image: centos8:latest
    steps:
      - run:
          name: Install basic tools
          command: |
            yum install -y git
      - checkout
      - attach_workspace:
          at: dist/
      - run:
          name: Test preparation
          command: .circleci/testprep.sh
      - run:
          name: Installation test
          command: find dist/ -name *.rpm | fgrep -v .src.rpm | xargs yum install -y
      - run:
          name: Distribution validity test
          command: |
            make disttest
      - store_artifacts:
          path: final/
          destination: /

  finalize:
    docker:
      - image: centos8:latest
    steps:
      - attach_workspace:
          at: dist/
      - run:
          name: Move to final location
          command: mv dist/* final
      - store_artifacts:
          path: final/
          destination: /

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test7:
          requires:
            - build
      - test8:
          requires:
            - build
      - finalize:
          requires:
            - test7
            - test8
     